<template>
  <q-card flat bordered square style="font-size: 0.8rem">
    <q-card-section v-show="title" class="bg-blue-grey-10 text-white text-bold q-py-sm">{{ title }}</q-card-section>
    <ReportHead v-show="head" :data="head" />
    <ReportTable :data="table" v-bind="$attrs" />
    <ReportFoot :data="foot" />
    <q-card-section class="q-pa-none q-pb-none">
      <div class="col-12 q-px-xl q-py-xs text-center bg-grey-1" style="font-size: 0.45rem">{{ footer }}</div>
    </q-card-section>
  </q-card>
</template>

<script>
import ReportTable from "components/Report/ReportTable";
import ReportHead from "components/Report/ReportHead";
import ReportFoot from "components/Report/ReportFoot";
import {to_format} from "assets/helpers";

export default {
  name: "ReportCard",
  components: {ReportFoot, ReportTable, ReportHead},
  props: ['head','foot','table','title'],
  data(){ return { time:null } },
  computed: {
    footer(){ return `Report generated by ${_USER.name} on ${this.time} using Smart Kitchen.` }
  },
  watch: {
    table: { immediate: true, deep: true, handler(){ this.time = to_format('ddd Do MMM YYYY @ hh:mm:ss A') } }
  }
}
</script>

