mklink /H .postcssrc.js milestone\smartkitchen\root\.postcssrc.js
mklink /H .styleci.yml milestone\smartkitchen\root\.styleci.yml
mklink /H babel.config.js milestone\smartkitchen\root\babel.config.js
mklink /H package.json milestone\smartkitchen\root\package.json
mklink /H quasar.conf.js milestone\smartkitchen\root\quasar.conf.js
mklink /H firebase.json milestone\smartkitchen\root\firebase.json
mklink /H .firebaserc milestone\smartkitchen\root\.firebaserc
mklink /H firestore.indexes.json milestone\smartkitchen\root\firestore.indexes.json
mklink /H firestore.rules milestone\smartkitchen\root\firestore.rules
mklink /H storage.rules milestone\smartkitchen\root\storage.rules
