<template>
  <q-card flat square style="font-size: 0.8rem">
    <q-card-section horizontal class="q-py-none print-only" v-if="report_text && report_image">
      <q-card-section class="col-5 flex flex-center"><q-img :src="report_image" style="max-height: 5rem;" :img-style="{ backgroundPosition:'left center' }" contain /></q-card-section>
      <q-card-section class="col-7 flex justify-end items-center"><pre class="text-right">{{ report_text }}</pre></q-card-section>
    </q-card-section>
    <q-card-section class="q-py-none text-center print-only" v-else-if="report_text || report_image">
      <pre v-if="report_text" class="text-center">{{ report_text }}</pre>
      <q-img v-if="report_image" :src="report_image" style="max-height: 5rem" class="text-center q-mb-sm" contain />
    </q-card-section>
    <q-card-section v-show="title" class="bg-blue-grey-10 text-white text-bold q-py-sm">{{ title }}</q-card-section>
    <ReportHead v-show="head" :data="head" />
    <ReportTable :data="table" v-bind="$attrs" />
    <ReportFoot :data="foot" />
    <q-card-section class="q-pa-none q-pb-none">
      <div class="col-12 q-px-xl q-py-xs text-center bg-grey-1" style="font-size: 0.50rem">{{ footer }}</div>
    </q-card-section>
  </q-card>
</template>

<script>
import ReportTable from "components/Report/ReportTable";
import ReportHead from "components/Report/ReportHead";
import ReportFoot from "components/Report/ReportFoot";
import {to_format} from "assets/helpers";

export default {
  name: "ReportCard",
  components: {ReportFoot, ReportTable, ReportHead},
  props: ['head','foot','table','title'],
  data(){ return { time:null } },
  computed: {
    report_text(){ return settings('report_text_' + _.snakeCase(this.title)) || settings('report_text') || null },
    report_image(){ return image_url(settings('_file_report_image_' + _.snakeCase(this.title)) || settings('_file_report_image') || null) },
    footer(){ return `Report generated by ${_USER.name} on ${this.time} using Smart Kitchen.` }
  },
  watch: {
    table: { immediate: true, deep: true, handler(){ this.time = to_format('ddd Do MMM YYYY @ hh:mm:ss A') } }
  }
}

function image_url(path){ return path ? location.origin + '/' + path : null }
</script>

